머신러닝 프로젝트

In [4]:
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x = np.random.randint(0,10,50)
y = np.random.randint(0,2,50)

print(x[:10])
print(y[:10])

train_x, test_x , train_y,test_y = train_test_split(x,y,test_size = 0.2, random_state=2025)

print(train_x[:10],len(train_x))
print(train_y[:10],len(train_y))
print(test_x[:10],len(test_x))
print(test_y[:10],len(test_y))
'''
feature_data = np.random.randint(0,10,50)
label_data = np.random.randint(0,2,50)

feature_train, teature_test,label_train, label_test = train_test_split(feature_data,label_data,test_size=0.3,random_state=42) #0.3 은 30%로 테스트
print(train_test_split)'''

[0 0 4 6 6 4 3 0 0 4]
[1 0 1 1 1 1 0 0 1 0]
[6 3 2 3 4 0 1 6 2 3] 40
[1 1 0 0 1 0 1 1 1 0] 40
[0 2 4 3 3 9 0 3 8 4] 10
[1 1 1 0 0 0 0 1 0 1] 10


'\nfeature_data = np.random.randint(0,10,50)\nlabel_data = np.random.randint(0,2,50)\n\nfeature_train, teature_test,label_train, label_test = train_test_split(feature_data,label_data,test_size=0.3,random_state=42) #0.3 은 30%로 테스트\nprint(train_test_split)'